"""Crear modelos

Revision ID: b68b8bc056be
Revises: 
Create Date: 2022-09-06 13:26:39.277278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b8bc056be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['username'])
    op.create_unique_constraint(None, 'usuario', ['correo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
